export type Guide = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  body: string[];
};

export type CategoryCard = {
  slug: string;
  title: string;
  description: string;
};

export const HOME_PATHS: CategoryCard[] = [
  { slug: "progression", title: "General Progression", description: "Pick a skill and follow the gear/level path from early to endgame." },
  { slug: "money", title: "Money Making Methods", description: "Every income stream in the game, from lazy minions to lowballing." },
  { slug: "ideas", title: "Give Me Some Ideas", description: "Not sure what to do today? Start here, browse everything." },
];

export const PROGRESSION_SKILLS: CategoryCard[] = [
  { slug: "mining", title: "Mining", description: "Powder, HOTM, and the long road to lategame." },
  { slug: "farming", title: "Farming", description: "Garden, pests, and crop money." },
  { slug: "fishing", title: "Fishing", description: "Sea creatures, lava, and trophy hunting." },
  { slug: "combat", title: "Combat", description: "Gear, Slayers, Dungeons, and Kuudra." },
  { slug: "minions", title: "Minions", description: "Passive income and collections." },
  { slug: "other-skills", title: '"Other" Skills', description: "Enchanting, Alchemy, Carpentry, Taming." },
  { slug: "foraging-hunting", title: "Foraging / Hunting", description: "Galatea, trees, and attribute shards." },
];

export const COMBAT_SUB: CategoryCard[] = [
  { slug: "slayers", title: "Slayers", description: "All 6 bosses, gear and routes." },
  { slug: "dungeons", title: "Dungeons (Catacombs)", description: "Floor 1 through Master Mode 7." },
  { slug: "kuudra", title: "Kuudra", description: "Crimson Isle raid boss progression." },
];

export const MONEY_METHODS: CategoryCard[] = [
  { slug: "lazy-money", title: "The Lazy Man's Methods", description: "Forge flipping and pet flipping. Minimal effort." },
  { slug: "flipping", title: "Bazaar / Auction Flipping", description: "The Art of Manipulation." },
  { slug: "rift-money", title: "The Rift", description: "20-50m/hr with the right setup." },
  { slug: "mining", title: "Mining", description: "Powder and gemstone income." },
  { slug: "farming", title: "Farming", description: "Crops and pest farming income." },
  { slug: "fishing", title: "Fishing", description: "Trophy fishing and sea creature income." },
  { slug: "foraging-hunting", title: "Foraging / Hunting", description: "Wood and attribute shard income." },
  { slug: "combat", title: "Combat", description: "Slayers, Dungeons, Kuudra income." },
];

export const SLAYER_LIST: CategoryCard[] = [
  { slug: "slayer-zombie", title: "Zombie Slayer", description: "Revenant Horror — the easiest." },
  { slug: "slayer-spider", title: "Spider Slayer", description: "Tarantula Broodfather." },
  { slug: "slayer-wolf", title: "Wolf Slayer", description: "Sven Packmaster." },
  { slug: "slayer-enderman", title: "Enderman Slayer", description: "Voidgloom Seraph." },
  { slug: "slayer-vampire", title: "Vampire Slayer", description: "Riftstalker Bloodfiend." },
  { slug: "slayer-blaze", title: "Blaze Slayer", description: "Inferno Demonlord — the hardest." },
];

export const DUNGEON_LIST: CategoryCard[] = [
  { slug: "dungeons-intro", title: "What is The Catacombs?", description: "The basics before you start." },
  { slug: "dungeons-starting", title: "Starting Out (F1-F3)", description: "The Watcher, Bonzo, Scarf, The Professor." },
  { slug: "dungeons-early-mid", title: "Early-Mid (F4-F6)", description: "Thorn, Livid, Sadan." },
  { slug: "dungeons-f7", title: "Floor 7", description: "Maxor, Storm, Goldor, Necron." },
  { slug: "dungeons-m1", title: "Master Mode Floor 1", description: "Nearly irrelevant — most players skip to M3." },
  { slug: "dungeons-m2", title: "Master Mode Floor 2", description: "Nearly irrelevant — most players skip to M3." },
  { slug: "dungeons-m3", title: "Master Mode Floor 3", description: "First floor where mastery gear starts to matter." },
  { slug: "dungeons-m4", title: "Master Mode Floor 4", description: "One of the best money floors." },
  { slug: "dungeons-m5", title: "Master Mode Floor 5", description: "" },
  { slug: "dungeons-m6", title: "Master Mode Floor 6", description: "" },
  { slug: "dungeons-m7", title: "Master Mode Floor 7", description: "The endgame." },
];

export const GUIDES: Guide[] = [
  {
    slug: "mining-early",
    title: "Beginning-Game Mining Progression",
    category: "mining",
    summary: "Getting to the Dwarven Mines and your first HOTM levels.",
    body: [
      "In the earlygame, you need to start progression. That means getting down to the Dwarven Mines, doing commissions, starting Mithril Powder, and getting basic armor.",
      "Armor",
      "Glacite Armor to start, transition into Yog Armor.",
      "Pickaxes/Drills",
      "Go down the Mithril Pickaxe line from Bubu, then at Heart of the Mountain (HOTM) 4, start buying and using Pickonimbus 2000s. You can also invest in a Mithril Drill (R226 or R326) for extra mithril powder at HOTM 2/3. These are highly recommended, and keep resale value, if you don't put them in your museum.",
      "Pets",
      "There's a lot of good mining pets. At this stage, focus on a Mythic Mithril Golem Pet and getting a Mole Pet online. If you just want xp, a Silverfish Pet is a fantastic option.",
      "Heart of the Mountain",
      "Ah, the first piece of torment and suffering, the Heart of the Mountain. Note that your first 5 commissions of the day get a BIG boost to your HOTM level. Upgrading your Heart of the Mountain unlocks access to new gear, new forge slots and items, new HOTM abilities, and so on.",
    ],
  },
  {
    slug: "mining-earlygame",
    title: "Early-game Mining Progression",
    category: "mining",
    summary: "HOTM 5 through 7 — Divan's Armor, Titanium Drills, and powder mining prep.",
    body: [
      "Once you have HOTM 5, I consider you at the \"early game\" stage of mining. Keep doing commissions, and start working on your Titanium Drill.",
      "Armor",
      "At HOTM 6, you can get Armor of Divan. At this point, start working on building it up. Get Gemstone Chambers, and get at least fine, preferably flawless, Gemstones in all slots. A note, if you are manually grinding these gemstones, put high priority on the topaz gems. Otherwise, Amber > Jade > Topaz.",
      "Pickaxes",
      "Drill Time! At HOTM 5, get a Titanium Drill DR-X455, then DR-X555 at 6.",
      "Pets",
      "At this point, get a Bal (Budget)/Crow pet (Rich), Goblin Pet, a Scatha Pet if you're rich or lucky, and an Armadillo Pet if not.",
      "For mithril powder (See below), get a Mithril Drill SX-R326. For gemstone powder, swap to a Topaz Drill KGR-12, or upgrading to a Jasper Drill X.",
      "You're officially out of \"earlygame\" mining when you have the above, as well as HOTM 7. At this point, get to powder mining!",
    ],
  },
  {
    slug: "mining-powder-mithril",
    title: "Powder Mining — Mithril",
    category: "mining",
    summary: "4m-12.5m Mithril Powder methods.",
    body: [
      "Alright so. Powder Mining. Powder sucks. Here's the next steps.",
      "Mithril Powder",
      "Methods require between 4m and 11.2m Powder. To get max xp, you need 12.5m Powder. To max every perk, you need 12.7m Powder.",
      "Methods",
      "Mithril Gourmand is your friend for this. As is having Dimensional Reforge on your armor. As is 2x Powder Event.",
      "When you have a Mithril Gourmand, pull out your drill and start mining. Mine until there's ~30s left in the timer, then use /tptodonexpresso to go directly to the dude, and feed that big back. Make sure you have:",
      "Required Equipment: Powder Pumpkin, Stellar Mithril Drill (R226 if really broke, 326 recommended), Spicy Goblin Omelette.",
      "If possible, find and stand next to a Fallen Star. Profit. Note — when hypermaxed, you can get 300-500k powder per Gourmand.",
      "Other Methods include: Raffle, Goblin Raid, Pure Mithril Mining, Dimensional Titanium Mining (Max peak efficiency, in the Abandoned Quarry), Powder Ghasts, Skymall (10x Golden and Diamond Goblin Chance).",
      "For an in-depth guide for Mithril Powder, here is TheUltimateNon's guide, in the Mining Cult server.",
    ],
  },
  {
    slug: "mining-powder-gemstone",
    title: "Powder Mining — Gemstone",
    category: "mining",
    summary: "8.2m-20m Gemstone Powder — your first real Money Making Method.",
    body: [
      "This will take up a lot of your time, but is also useable as your first Money Making Method, capping somewhere around 10-15m/hr, if you're efficient about it.",
      "Gemstone Powder",
      "Methods require between 8.2m and 16m Powder. To get max Skyblock XP, you need 20m Powder. To max every perk, you need 21.2m Powder.",
      "Once you have your HOTM 6, your Topaz/Jasper Drill, Great Explorer 20, and as much Mining Spread as you can, you're good to start making a bit of money. There's two ways to do this:",
      "Option A — Sludge Juice Mining. At ~1800 coins per piece, and a 0-effort way to obtain it, this is a decent option.",
      "Option B — Precursor Mining. Values jumping between 50k and 400k apiece, Automaton parts sell AMAZINGLY.",
      "Equipment: Jungle Pickaxe (Odawa or Auction), Powder Drill (to open chests).",
      "Pets: Bal Pet, Mining Pet (Budget — Armadillo. Rich — Scatha, Rare or Legendary).",
      "Autopet Rules — On Rod Cast, Equip Bal Pet. On gain Mining XP, equip Scatha/Armadillo. Use Bal pet for Mining Armor (Budget), Glossy Mineral (Rich).",
      "HOTM effects — Great Explorer, Mole, Powder Buff, Front Loaded, Core of the Mountain 6. Pickobulus until HOTM10, then Sheer Force.",
      "Attributes — Zombie Miner (extra mining speed, low prio), Hideonleaf (50 Block Fortune, small boost), Hideoncave (50% extra item chance, top prio), Cuboa (20% buff to box attributes, mediocre prio), Thyst (10% gemstone powder buff, top prio), Quartzfang/Iguana/Tiamat (lower prio, minor buffs).",
      "The Method — Go to the Jungle or Precursor Remnants. Option A: mine with your Jungle Pick, collect chests, Sludge Juice flows in. Move your mouse in circles with your mining spread to optimize rates. Option B: exact same, but use a drill/normal pickaxe, collecting Automaton parts to sell (or use for Nucleus Runs).",
      "For more in-depth details, TheUltimateNon has a Gemstone Powder Guide.",
    ],
  },
  {
    slug: "mining-powder-glacite",
    title: "Powder Mining — Glacite",
    category: "mining",
    summary: "4.7m-24m Glacite Powder — the gear-heaviest powder grind.",
    body: [
      "Bad news. There's more. To do Glacite Powder efficiently, you need a LOT more gear.",
      "Glacite Powder",
      "Methods require between 4.7m and 24m powder. To get max xp, you need 20m powder. To max every perk, you need 34.5m powder.",
      "Equipment: Budget — Auspicious Titanium Drill DR-X655. Rich — Lustrous Divan's Drill, Jaded Divan's Armor with full Perfect Gemstones, Ice Cold enchant on armor if rich, Blazing Titanium Equipment or Pendant of Divan, Sapphire Cloak, Jade Belt, and Dwarven Handwarmers.",
      "Pets: Bal Pet, Glacite Golem. Autopet — On Rod Cast, Bal/Crow Pet. On mining xp, Glacite Golem. Use Bal/Crow for ability and Golem for general use. Can add a Mammoth for survivability in tunnels.",
      "The Methods",
      "Commission Gaming — with a measly 8.5m Mithril and 15.8m Gemstone Powder, you can start just mining for commissions. When claiming comms, make sure you're maximizing powder and loot (personally skip Umber and Tungsten corpses unless you have money to spare, since they need keys).",
      "Vanguard Gaming — party time! Form a party of 4 players with a good mining setup. Whenever you find a mineshaft, warp in, get/buy the keys, and loot the big Corpses. Powder reqs: 8.5-11m Mithril, 7.3-15.8m Gem, 3.4-7.2m Glacite.",
      "Excavator Machine — use a Perfect Chisel with Perfect Citrine, claim and collect all the Fossils etc. Skip if the fossil is a Helix fossil, focus on the powder drops. Use SkyHanni's Excavator Solver. Different gemstones have different effects — for optimal money, use the Citrine, which highlights existing treasures.",
    ],
  },
  {
    slug: "mining-lategame",
    title: "Lategame Mining",
    category: "mining",
    summary: "Once you're through powder mining, this is where the real money is.",
    body: [
      "Yes. Yes you can. You are now Lategame Mining. Make some money.",
      "Due to the existence of the guides in Mining Cult, I will instead make reference links to each notable guide.",
      "The Methods: Mycelium/Red Sand, Divan Gold, Ore Mining, Mineshaft Mining, Obsidian, Fairy Grottos, Netherrack, Hollows Coal, Endstone, Flint, Glowstone, Cobblestone.",
    ],
  },
  {
    slug: "farming-intro",
    title: "Starting the Garden",
    category: "farming",
    summary: "Clearing your first plot, visitors, and pests.",
    body: [
      "Alright so. Farming. This one may need some work, due to the changes, but here goes:",
      "Starting the Garden",
      "Clear your first plot. If you can, select the plots to either side of your barn. This will be explained later.",
      "Plant any plot you choose, and start farming with an advanced farming tool.",
      "Note — you cannot use Turbo-Crop enchants until you have specific medals in their crop.",
      "You gain Garden Experience from Crop Milestones (farming unique crops on the Garden) and from serving Visitors. You want to get as much Garden Experience as possible.",
      "Q — What are Visitors? A — Visitors are NPCs you've met in your travels across the Skyblock World. They will visit your Garden, and ask you for crops. In exchange, they will give you Copper, which can be used in the Skymart (/desk command) to purchase various enchants, tools, and other materials.",
      "Q — What crop should I farm? A — Depends on what you want to do. For experience, Mushrooms are best. For money, that depends fully on what you're doing.",
      "Pests: destroy them with a Vacuum, gaining a number of crops and some Farming XP. If you leave them for too long, they start draining your farming fortune. You can have a maximum of 8 pests active at once.",
    ],
  },
  {
    slug: "farming-tools",
    title: "Tools of the Trade (Farming)",
    category: "farming",
    summary: "The full armor, equipment, enchant, and pet progression for Farming, plus a look at the Greenhouse.",
    body: [
      "There's a LOT of different armor sets, tools, etc., related to farming. This breaks down the requirements and options of each one.",
      "Armor Progression: Farm Suit (Farming 3), Farm Armor (Farming 10), Rancher's Boots (Farming 21), Melon Armor (Farming 25), Cropie Armor (Farming 30), Squash Armor (Farming 35), Fermento Armor (Farming 40), Helianthus Armor (Farming 50). Due to the introduction of the Sundial, a normal profile player can skip Rancher's Boots, as the Sundial replicates their functionality and Fermento Armor is better in all ways. Ironman can still take this step.",
      "Equipment Progression: Pesthunter Equipment (good for Pest Farming), Pest Vest (best Pesthunting piece), Lotus Gear (standard for Farming Fortune, from Skymart), Blossom Gear (upgrade to Lotus, best in series for FF, from Skymart), Zorro's Cape (best Farming Cape during Jacob's Contests).",
      "Armor, Equipment, and Tool Enchants: Turbo-Crop 3-5 (ASAP as available, all tools), Turbo Gourd (when available), Delicate (ASAP), Cultivating (ASAP), Dedication (when able to afford), Sunset (armor ultimate enchant), Pesterminator (high priority, all armor), Crop Fever (tier 1 ASAP), Feast (when able to afford), Bug Blender (low priority, vacuum), Enchanted Turbo Gourd (desired), Green Thumb (lowest priority, equipment).",
      "Armor, Equipment and Tool Reforges: Skymart Brochure (100 Copper, cheap early FF), Overgrown Grass (rare visitor drop, best armor reforge), Squeaky Toy (Field Mouse drop, cheap on BZ, for Pesthunter Gear), Burrowed Spores (rare Mushroom drop, best FF for Equipment), Blessed Fruit (Smithmonger, best for xp/easier to get, all tools), Golden Ball and Overpriced (Harvest Feast drops, for grinding and your Overbloom tool).",
      "Vacuums: linear progression from the Skymart. Optimal vacuum is a Beady Infinivacuum Hooverius, with a Hedgehog pet or maxed Praying Mantis attribute, allowing you to one-shot pests. Apply Bug Blender when available (expensive).",
      "Pets: Elephant (Legendary only, 150 FF at max level), Mooshroom Cow (110 FF + 0.7 per 20 Strength, gives a Mushroom on crop break, best for money and FF at high strength), Rabbit (best for Farming Wisdom/xp), Hedgehog (best for killing Pests, +100 FF against pests), Slug (poor man's Mosquito), Mosquito (most Bonus Pest Chance, buffs pest vinyls), Rose Dragon (best in series for everything, replaces Hedgehog and Mooshroom Cow).",
      "If focused on levelling farming, use Rabbit. For money, Mooshroom Cow. For pests, Mosquito ~3s before spawn, Hedgehog after spawn.",
      "Accessories that affect Farming Fortune: Atmospheric Filter, Agarimoo Artifact, Magic 8 Ball, Helianthus Artifact, Anita's Artifact.",
      "Unique Tools: each crop has its own special tool (250 Copper in the Skymart), upgradeable twice with Jacob's Tickets (64 for T2, 256 for T3) and crop-specific amounts.",
      "Others: Sundial (replaces Rancher Boots for speed control), Day Saver / Night Saver (time control — combine to farm Sunflower/Moonflower and their pests), Squeaky Mousemat (pitch/yaw control), Buzzybee's Fantabulous Disco Destination (gathers pests to one spot), Sprayonator.",
      "The Greenhouse: a newer addition letting you grow crops and combine them into Mutations. AVRG's comprehensive Greenhouse Guide covers setup; SkyMutations and Toronto websites are good research tools. Ethereal Vines expand your greenhouse (more vines = more plots = more mutation space). You'll also need legendary Mutations to purchase a Rose Dragon Egg.",
    ],
  },
  {
    slug: "farming-rushing",
    title: "Farming — The Rushing Way",
    category: "farming",
    summary: "Skip steps and buy your way to Farming level.",
    body: [
      "This method is designed to skip as many steps as you can, and speed up the process. Generally, if you have more money and just want to progress the skill, this is the optimal method.",
      "Armor: if you don't already have Farming 25, just buy whatever farming armor. The most important thing for now is a Sundial. Once you have your Sundial and Garden 9, build Melonkingde's old but gold Slanted Downward Spiral farm. Farm Mushrooms using that until Farming 40, and buy Fermento Armor. If you really want to be lazy, skip Fermento, farm until Farming 50, and buy Helianthus Armor. Best reforge for armor is Mossy (Mantid if only 1 set / pest farming).",
      "Tools: if you're rich, find a seller and buy yourself a hypermax Fungi Cutter, then figure out your money-making crop and buy that. Best reforge for tools is Blessed for XP, or Bountiful for money.",
      "Equipment: same as normal — Lotus into Blossom Gear, or if pesthunting (better for money), the Pesthunter Equipment and Pest Vest. Optimally use both sets, swapping when pest farming.",
      "Pets: the \"Rushing\" way is to flat-buy a level 100 epic+ Rabbit, use it till Farming 40 (or 50), then buy a Hedgehog, Slug/Mosquito, and Mooshroom Cow — or skip Hedgehog/Cow and go straight to Rose Dragon.",
      "Crops to farm: Garden 1-3 — Wheat, Carrot, Potato. Garden 4-8 — Pumpkin, Sugarcane, Melon, Cactus, Cocoa. Garden 9-15 — Mushroom, mushroom, mushroom. Garden 15+ — figure out your best money-making crop, using Elitebot to help decide.",
    ],
  },
  {
    slug: "farming-how-to",
    title: "How Do I Actually Farm?",
    category: "farming",
    summary: "Custom farms and what to grow.",
    body: [
      "Now how do you farm? Simple answer: Custom Farms! There's a number of notable \"Custom Farms.\" While there's no single perfect one, here's a couple good ones: MelonkingDE's SDS Mushroom Farm, GroveManDan's Superfarm 7.0, Draip's Angled Pest Design, the New and Improved Melon/Pumpkin Design.",
      "There are more, and there will be more — realistically, find the farms, find the videos, find what works for you. Suntzulegacy's island has a lot of good ones.",
      "As to what to farm: prices range a lot. During a Harvest Feast, Feast drops are universally better than any generic crop. For \"generic\" crops, wheat, melon, and the flowers tend to be the general best for income.",
      "Other Farming Resources: the Farming Hub, Elite Skyblock Farmers, and Farm Designers discord servers.",
    ],
  },
  {
    slug: "farming-pests",
    title: "Pest Hunting",
    category: "farming",
    summary: "Bonus Pest Chance, setups, and full autopet rotation.",
    body: [
      "Pests are a new-ish feature. As stated before, pests spawn, you kill them, you get loot; no kill, you lose Farming Fortune.",
      "Pests can be killed with a Vacuum. Magic Find affects most mob drop rates, but for Pests, Farming Fortune boosts the rate of their rare drops as well as the number of crops they drop.",
      "Bonus Pest Chance is a stat added with Pests — your Armor, accessories, pet, and other sources increase your bonus pest chance, increasing the number of pests that can spawn at once.",
      "Mods: Skyhanni (Pest Timers, Pest Locator, Chunk Locations, key shortcuts), Skytils (custom key shortcuts).",
      "Setup: 4/4 Fermento/Helianthus Armor (Mantid), Pesterminator (5-6), Beady Infinivacuum Hooverius, Sprayonator, 3/4 Squeaky Pesthunter Equipment with a Pest Vest, Pesthunter Relic, tool of choice for crop of choice.",
      "Optional Setup / Pets: Extra set of Fermento/Helianthus Armor (Mossy Bandana), Mooshroom Cow Pet (Green Bandana), Mosquito Pet (Brown Bandana, replaces Slug), Rose Dragon Pet (Green Bandana, replaces Hedgehog and Mooshroom Cow).",
      "Autopet Rules are the key to success:",
      "2 sets of armor, Rose Dragon variant — On Equip Mantid Helianthus: Mosquito. On Equip Mossy Helianthus: Rose Dragon.",
      "2 sets of armor variant — On Equip Mantid Helianthus: Mosquito. On Equip Mossy Helianthus: Hedgehog. On Cast Rod: Mooshroom Cow.",
      "1 set of armor variant — On Rod Cast: Mooshroom Cow (unless Mosquito/Slug active). On Rod Cast: Mosquito/Slug (unless Hedgehog active). On Rod Cast: Hedgehog (unless Mooshroom Cow active).",
      "How it works: build a Pest Farm (Chissl's or Draip's are popular). Equip your Mantid Helianthus to swap to Mosquito. When pests spawn, /setspawn and equip Mossy Helianthus to swap to Hedgehog. Enter the plot and vacuum them. Cast Rod to equip Mooshroom Cow and warp back with /warp garden. Repeat.",
      "Temporary Buffers: Harvest Harbinger Potion, Douce Pluie De Stinky Cheese Potion, Refined Dark Cacao Truffle, Philip Pest Farming Bonus, Sprayonator, Magic 8-Ball, Atmospheric Filter.",
    ],
  },
  {
    slug: "fishing-beginning",
    title: "Fishing Progression — Beginning (0-19)",
    category: "fishing",
    summary: "From the Fish Family to Stridersurfers.",
    body: [
      "Before Fishing 10, fishing is pretty miserable. Collecting the Fish Family to give to Coral, then using Clay or Fishing Minions for the remaining xp levels, is recommended.",
      "Earlygame (10-19): with the release of the Lotus Atoll, fishermen can rejoice — a new location with passable xp rates. The Atoll includes the Lotus collection, Trophy Frogs, Explosive Lily Pads, and new sea creatures with acceptable xp. You can comfortably fish here until ready to lava fish, though moving on at Fishing 19 is recommended to pass the grind faster.",
      "Armor Progression: Fishing 0-12 — 3/4 Angler Armor, Water Hydra Head. Fishing 13-16 — Salmon Armor. Fishing 17-20 — Sponge Armor. Fishing 20 — Diver's Armor. Fishing 24 — Shark Scale Armor.",
      "Water Fishing Rod Progression: Fishing 0-4 — Vanilla rod, up to Fishing 24+ — Rod of the Sea. If omega rich, Giant Fishing Rod.",
      "Equipment Progression: Budget starter is Fisherman Set or Angler Set. Standard is Ichythyic Equipment with a Delirium Necklace or Frozen Amulet. Comfort is Finwave Equipment. Rich is the Gillsplash Set.",
      "Pet Progression: Ammonite (best for Sea Creature Chance), Flying Fish (best for Fishing Speed, best overall lategame pet), Squid Pet (xp pet), Hermit Crab (best for Hotspot/Treasure Fishing), Megalodon (best for Fishing Festivals), Baby Yeti (best for Jerry Island Fishing).",
      "What to fish: Fishing 0-9, focus on Spooky/Fishing Festival. Fishing 10-18, fish up creatures in the Lotus Atoll — tolerable xp, and includes a run to the Crystal Hollows (365,166,530) to throw worms into a pit with Worm Bait for extra xp.",
      "Fishing 19: Stridersurfers, the best source of fishing xp in the game. Once you hit this point, you're in the \"beginning of midgame.\"",
    ],
  },
  {
    slug: "fishing-midgame",
    title: "Fishing — Midgame and Onward (19+)",
    category: "fishing",
    summary: "Lava rods, Trophy Fishing prep, and endgame equipment.",
    body: [
      "At this stage, your main objective is experience and gear upgrades.",
      "Fishing Rods (Lava): Fishing 19-26 — Topaz Rod (technically beats the Magma Rod in speed, but needs HOTM 5). Fishing 27-29 — Magma Rod. Fishing 30-34 — Inferno Rod. Fishing 35+ — Hellfire Rod.",
      "What to fish: at Fishing 19, unlock Stridersurfers — go to Galatea, navigate to -693,121,79. Use the Topaz Rod there.",
      "As you level up, start Trophy Fishing in the nether. Before Fishing 27, get requirements for Bronze Hunter — no sea creatures in the pool at that point, making it far less painful to get all the powder and loot (personally skip Umber/Tungsten corpses unless money to spare).",
      "Armor Progression: Fishing 27 — Slug Boots. Fishing 28 — Moogma Leggings. Fishing 33 — Flaming Chestplate. Fishing 35 — Taurus Helmet. Fishing 36 — Thunder Armor. Fishing 45 — Magma Lord Armor. (The 4 pieces from 27-35 make up the Lava Sea Creature Set — replaced fast, so a well-upgraded Shark Scale set until 36/Thunder can be preferable.)",
      "Equipment Progression: follow earlygame stuff up to Gillsplash. Fishing 36 — replace Delirium Necklace with Thunderbolt Necklace or Frozen Amulet. Fishing 45 — Magma Lord Necklace.",
      "Endgame prerequisite: Hyperion (to kill Thunders and Lord Jawbusses — a Midas Staff can substitute in a pinch, or a Flaming Flay for easier attribute shard catching).",
      "Pet Levelling: use autopet on combat entry to level high-value pets (like Blue Whale) for sale. Alternate options: max Treasure Chance, or look into Squid Fishing.",
      "Reach out in the main server for more info.",
    ],
  },
  {
    slug: "fishing-trophy",
    title: "Trophy Fishing",
    category: "fishing",
    summary: "Trophy Chance sources, quality boosters, and where to catch every Trophy Fish and Frog.",
    body: [
      "With the addition of the Lotus Atoll, trophy fishing has become a much more present part of the game.",
      "Before you Start: try to get the Bronze Trophy Armor from Odger in the Crimson Isle, or a Treasure Hook (Fishing 25+), so sea creatures don't muddle the pool. Without either, catch 10 sea creatures (personal cap), leave them alive, and keep fishing — same effect as hunter armor.",
      "Trophy Chance sources — Rods: Starter Lava Rod (Fishing 10, 5 TC), Magma Rod (Fishing 27, 15 TC), Inferno Rod (Fishing 30, 20 TC), Hellfire Rod (Fishing 35, 25 TC).",
      "Armor: Bronze/Silver/Gold Hunter tiers, Gold/Diamond Froggles (Wormhole-only TC), Red Sweater (4 TC).",
      "Equipment: Fisherman's Set (1 TC/pc, 4 total).",
      "Pets: Spinosaurus (0.05/lv + 50% during rain), Frog Pet (Mythic only, 0.05/lv), Kuudra Pet (0.2/lv, Uncommon, only in Crimson Isle).",
      "Accessories: Odger's Teeth and Ribery's Rewards, for trophy fishing/frog milestones.",
      "Reforges: Geometric Oddity (1-4 TC on Froggles only).",
      "Other sources: Hotspots and Hotspot Hooks (5 TC), Fire Eel Shard (2-20 TC), Lotusfish Shard (1-10 TC on Atoll), Umberella (5-10 TC), Trophy Line, Hot Bait, Frogcoin's Blessing, Pearl of the Lotus.",
      "Quality Boosters (gold/diamond chance): Radiant Lure (from Gemma), Golden Frog (Flipflopper), Diamond Frog (Seashine), Mythic Frog Pet, Spinosaurus Pet, Golden/Diamond Froggles (wormhole only), Lotus Crown, Barrel of Riches, Charm enchant.",
      "Trophy Fish locations: caught anywhere with no reqs — Blobfish, Golden Fish, Lavahorse, Mana Ray (needs 1200 mana), Slugfish (bobber in lava 20s), Sulphur Skitter (near sulphur ore), Vanille (starter lava rod, no enchantments), Obfuscated 1-3 (chained bait requirements).",
      "Location-specific: Flyfish (Blazing Volcano, 8 blocks below player), Karate Fish (in the dojo), Moldfin (Mystic Marsh/Scarleton), Skeleton Fish (Burning Desert/Dragontail), Soul Fish (Stronghold), Steaming-Hot Flounder (near a geyser, in the volcano), Volcanic Stonefish (Blazing Volcano).",
      "Common strategies: Karate+Moldfin at the dojo/Mystic Marsh border. Volcanic Trio — stand high in the volcano near a geyser for Steaming-Hot Flounder, Volcanic Stonefish, and Flyfish at once (bonus Gusher right after an eruption). Flyfish+1 — spots beside the volcano catch flyfish and moldfin/skeleton fish together.",
      "Trophy Frogs: caught all over the Lotus Atoll, and much simpler than Trophy Fish — better spawn rates, 6 fewer species. Anywhere: Common Frog, Leap Frog (while jumping), Wetlands Frogs (during rain), Blessed Frog (under Frogcoin buff), Bullfrog (Red Sweater), Sea Frog (underwater).",
      "Unique: Exploding Frog (merge lilypads), Reality Hopper (fish in a Wormhole wearing Froggles), Cave Frog (Lotus Eater's Cave), Highlands Frog (Lotus Highlands), Tree Frog (standing on leaves), Puddle Jumper (rod on a Puddle Jumper sea creature, fly through the atoll).",
      "Common strategies: Trees and Caves — 80/70/2 has leaves in the cave area, catching both at once. Highlands Trees is another good combo spot.",
    ],
  },
  {
    slug: "combat-early",
    title: "Beginning the Game — Combat",
    category: "combat",
    summary: "Mercenary Armor to the Void Sword, and understanding Magic Power.",
    body: [
      "Once you have a LITTLE bit of money, you'll want Mercenary Armor and a Raider Sword — enough to start surviving against Spiders etc. Make your way to the End Islands and start killing Endermen and Zealots.",
      "Talk to Elizabeth and claim your one free Booster Cookie — play as much as you can, since you get a lot of benefits from them, including the desirable God Potions.",
      "When you can kill Endermen, talk to the Lone Adventurer and progress his questline. For 200k, he sells the Void Sword, your staple into earlygame. Get the Ender Equipment from drops: Ender Necklace (normal Endermen), Ender Gauntlet (Ender Nodes, also decent money), Ender Belt (Obsidian Defenders), Ender Cloak (Seers).",
      "Magic Power is a stat gained from Accessories, from a huge variety of sources. To find your cheapest missing accessory, use the /missing username:[you] profile:[profile] command in the relevant Discord channel.",
      "Speak with the Thaumaturgist to select a Power Stone. Earlygame, use Warrior or whatever's free. Eventually you'll want: Sighted (Ender Monocle, for Mage/high int, from Seers), Silky (Luxurious Spool, for melee/crit damage, from Arachne), Bloody (Beating Heart, from Sven Packmaster), Scorching (Scorched Books, melee, upgrade to Furball, from Inferno Demonlord), Shaded (Dark Orb, Catacombs Floor 5 reward), Hurtful (Magma Urchin, best in series for melee, Crimson Isle minibosses), Bizarre (Eccentric Painting, best for Mage, Dark Auction), Fortuitous (free, but required if using a Terminator).",
      "There IS a cap on Magic Power, but it's ultra lategame.",
      "To grow your Accessory Bag: Redstone Collection first (easiest), then the Redstone Miner's Quest, then the profile upgrade via Elizabeth, then Jacobus (expensive), then attributes like Hideonring.",
      "Objective of this stage is to get you to one-shotting Zealots. After that, you have a lot of routes to go.",
    ],
  },
  {
    slug: "combat-general",
    title: "General Combat Guide",
    category: "combat",
    summary: "Armor sets, helmet options, and the best generalist weapons in the game.",
    body: [
      "This guide covers everything else combat-related: Crimson Isle bosses, Mythological Ritual, Sea Creatures, and detail on the \"Generalist\" loadouts referenced throughout the Slayer guides.",
      "Armor Options: start with Mercenary Armor from Rosetta. Then Ender Armor with a Void Sword and Dragon Shortbow. Then Dragon Armor — Unstable is cheap and stable (Young/Wise for mage, Strong is a weak set bonus, Superior if rich). After that, combat-specific sets like Slayer or Dungeon sets.",
      "Then there's three armor sets from Kuudra that carry you to endgame: Crimson Armor (melee, set bonus Dominus — melee attacks stack 2-3x weapon damage), Aurora Armor (mage, set bonus Arcane Energy — sneak fires homing missiles, plus 40 ability damage and 1400 intelligence), Terror Armor (archer, set bonus Hydra Strike — stacking damage/arrow speed, extra arrows at 10 stacks).",
      "Helmet Options: Crimson/Terror Helmet (worst at Hot, second-best at Fiery/Infernal). Warden Helmet (second-highest raw damage, but kills speed). Wither Goggles (the real mage option). Primordial Helmet (budget but high stats and magic find).",
      "Weapons — From Beginning to End: earlygame, a Raider Sword bridges to Void Sword, which leads to Aspect of the Dragons.",
      "Highlight 1 — Bouquet of Lies. Look funny beating enemies with flowers, but it's not: 220 base weapon damage, 300 strength, 50 crit damage, plus the Petal Barrage ability at 10% current health cost.",
      "Highlight 2 — Daedalus Blade. Underwhelming raw stats (4 damage/taming level, capped 240), but copies your active pet's combat stats — effectively getting Chimera 5 for free, stacking with the actual Chimera enchant. Also grants extra Mythological Ritual damage and magic find.",
      "Highlight 3 — Hyperion. Does everything: mobility, big AOE damage, shielding/healing. One of three true endgame weapons.",
      "Highlight 4 — Terminator. Triple-shot bow with huge damage and speed — a monster for anything damageable by bows.",
      "Highlight 5 — Glacial Scythe. Cheap, annoying, great for clearing Zealots and the obnoxious wise dragons.",
      "Highlight 6 — Giant's Sword. Usually overpriced junk, but excellent at killing clusters too strong to one-shot (bats, sea creatures, Terracottas). 500 base damage, extra swing range, 100,000 ability damage in a huge AOE.",
      "Mythological Ritual: with Diana 2.0, it has its own armor — Challenger and Mythos Armor. Not much point until ~800-1000 magic power, then get a legendary Golden Dragon Pet. The Daedalus Blade is the best sword for Diana due to the huge magic find from pet stat copying — with a Golden Dragon that's an absurd number.",
      "Lava Sea Creatures: Hyperion is the standard tool here (enjoy dying to Lord Jawbus repeatedly). Other options: Flaming Flay, hypermax Zombie Commander Whip, or a Midas Staff if broke (though wasteful).",
    ],
  },
  {
    slug: "slayer-overview",
    title: "Slayer Overview",
    category: "slayers",
    summary: "All 6 bosses at a glance, and useful quality-of-life milestones.",
    body: [
      "Slayers are bosses, spawned by killing a certain xp amount of their related mob type. Each Slayer has its own drops, resources, and gear/weapons/utility items. Start a Slayer quest by talking to Maddox.",
      "The 6 slayers: Revenant Horror (Zombie, easiest). Tarantula Broodfather (Spider, second/third easiest). Sven Packmaster (Wolf, third/second easiest — no T5 yet). Voidgloom Seraph (Enderman, second/third hardest). Riftstalker Bloodfiend (a Rift-exclusive vampire boss, very unique). Inferno Demonlord (Blaze, vastly considered the hardest).",
      "Quality of life milestones: Maddox Batphone (Sven level 3 — call Maddox without talking to him). Autoslayer (Level 6 in each of Revenant/Tarantula/Sven/Voidgloom — auto-starts quests on completion).",
    ],
  },
  {
    slug: "slayer-zombie",
    title: "Zombie Slayer — Revenant Horror",
    category: "slayers",
    summary: "The easiest of the bosses.",
    body: [
      "Revenant Horror is the easiest of the bosses by far. Tier 1-4 you can likely do with your \"starter gear\" and at least 150-200 magic power. Tier 5, recommend a minimum of 500 magic power and at least Shadow Assassin armor (preferably more).",
      "Unique Equipment: Wand of Healing/Mending/Restoration/Atonement (Slayer 1/3/6/7), Revenant Falchion (Slayer 3), Crystallized Heart helmet (Slayer 3), Revenant Armor (Slayer 4/5), Reaper Falchion (Slayer 6), Revived Heart (Slayer 6), Reaper Armor/Mask/Scythe (Slayer 7), Halberd of the Shredded (Slayer 8), Warden Helmet (Slayer 8).",
      "Generalist Route: use your standard dungeon or Nether gear — an easier time overall than a Specialist route, without needing a dedicated setup.",
      "Specialist Route: Revenant Armor/Falchion, upgraded to Reaper Armor/Falchion (+Reaper Mask), upgraded to Warden Helmet + Halberd of the Shredded. Grants far more survivability and a huge damage boost, but only against zombies. Only optimal if you'll grind this content a lot.",
      "Items useful outside of Slayer: Crystallized/Revived/Reaper Mask are fantastic healing armor pieces (double vitality), usable in Dungeons and general combat. Reaper Scythe is a budget option for hitphase on Voidgloom Seraph. Warden Helmet is one of the strongest helmets for damage outside of dungeons.",
    ],
  },
  {
    slug: "slayer-spider",
    title: "Spider Slayer — Tarantula Broodfather",
    category: "slayers",
    summary: "Web of Lies, Bat Barrage, and Noxious Paralysis at higher tiers.",
    body: [
      "Tarantula Broodfather is the second set of bosses, and the next easiest since bugs were resolved.",
      "Tier 1-2 is fairly easy. Tier 3+ introduces Web of Lies — 2/3/4 eggs with 3/6/9 HP each spawn, and the boss is invulnerable while they live (or until a 15s timer passes). Tiers 4-5 add Bat Barrage (a bat swarm dealing 1-2% max health/sec per bat) and Noxious Paralysis (lowers speed cap and reduces healing).",
      "Against tiers 4-5 healing options are minimal — Tarantula/Primordial Chestplate and Tarantula Pet are the main ones.",
      "Requirements: consistently killing T5 Revenants (Shadow Assassin armor, Tarantula Chestplate, Reaper Mask) is a good benchmark.",
      "Unique Gear: Recluse Fang (Slayer 2), Tarantula Armor/Fang (Slayer 4), Spider Shortbow (Slayer 5), Scorpion Foil (Slayer 6), Mosquito Shortbow/Primordial Armor (Slayer 7), Sting/The Primordial (Slayer 8).",
      "Generalist Route: low-tier — dungeon legs/boots, tarantula chestplate, reaper mask line helmet. High-tier — Reaper Mask and Tarantula Chestplate until ~900mp, then Burning Tier Crimson Armor. Use a Spider/Mosquito Shortbow, or a Terminator (spreadshot for egg sacs, more RNG-reliant).",
      "Specialist Route: Tarantula Armor, eventually Primordial, but requires investing in a set with limited external use.",
      "Items useful outside of Slayer: Tarantula/Primordial Boots (mobility), Tarantula/Primordial Helmet (strong budget helmet, ~20% less than Warden), The Primordial (#1 slayer utility equipment), Shriveled Bracelet (powerful glove-slot item).",
    ],
  },
  {
    slug: "slayer-wolf",
    title: "Wolf Slayer — Sven Packmaster",
    category: "slayers",
    summary: "Only 4 tiers, widely considered the easiest.",
    body: [
      "Sven Packmaster is the third set of bosses, with only 4 tiers. Its abilities are true damage (bypasses defense) and Call the Pups (spawns 6 pups one by one at 50% health, becoming invulnerable while spawning).",
      "Requirements: slightly harder than Revenant Horror, but not much. ~400mp and Shadow Assassin is plenty if you're smart about the pups.",
      "Unique Gear: Radiant Power Orb (Slayer 2), Maddox Batphone/Shaman Sword (Slayer 3), Mastiff Armor (Slayer 4), Weird Tuba (Slayer 5), Mana Flux Power Orb/Pooch Sword/Armor of the Pack (Slayer 6), Overflux/Plasmaflux Power Orb (Slayer 7).",
      "Generalist Route: this boss isn't much of a challenge.",
      "Specialist Route: Mastiff/Pooch does the trick easily, but is generally slower than generalist routes due to no further upgrades. Do not use Armor of the Pack — it's bad.",
      "Items useful outside of Slayer: the Power Orbs are a powerful line of healing items used in a variety of setups. The Weird Tuba is a decent buff item, stronger when upgraded to Weirder Tuba. The Pooch Sword + Mastiff Armor is the cheapest set for Ghosts. Mastiff Armor can also clear the Campfire Trials.",
    ],
  },
  {
    slug: "slayer-enderman",
    title: "Enderman Slayer — Voidgloom Seraph",
    category: "slayers",
    summary: "Only 4 tiers, but the biggest power jump in the game.",
    body: [
      "Voidgloom Seraph is the fourth set of bosses. Also 4 tiers, but the power jump from Sven to Voidgloom is astronomical — each tier has major changes and gets much harder.",
      "Requirements: Tier 1 is straightforward with a general combat setup. Tier 2 needs a proper setup (people run Shadow Assassin, Rock Pet, Revived Heart/Reaper Mask). Tier 3 basically needs a full setup — 600+ MP recommended. Tier 4 100% requires a full setup — 750+ MP recommended.",
      "The Setup — Generalist Route (there IS one, but a specific one): Burning 5*+ Crimson Armor, Warden Helmet, full fuming, full recomb, pref. G6P6, Ferocious Mana 5+, 3pc Wisdom 5, 1pc Refrigerate 3-5. Vorpal Katana (broke) or Atomsplit Katana (anything more). Healing: Florid Legendary Ender Dragon (second-best) or Legendary Lion (budget DPS), Enderman pet if failing to survive. 800+ Magic Power. Hitphase: Terminator with explosive arrows, or Reaper Scythe with Tank Zombies (M1-3).",
      "Specialist Route: identical to Generalist, but 100-200mp lower, using 4pc Final Destination Armor instead. Note: 5k kills for T3, 10k min/25k preferred for T4.",
      "Unique Gear: Voidwalker Katana (Slayer 1), Voidedge Katana (Slayer 3), Final Destination Armor (Slayer 4), Juju Shortbow/Vorpal Katana/Gloomlock Grimoire (Slayer 5), Gyrokinetic Wand/Aspect of the Void/Atomsplit Katana (Slayer 6), Etherwarp Conduit/Terminator (Slayer 7).",
      "Items useful outside of Slayer: Juju Shortbow (decent for dungeon tanks), Gyrokinetic Wand (very helpful for swarmy content — Arachne, F4/6, etc.), Aspect of the Void (upgrade to Aspect of the End, Etherwarp Conduit for precise teleports), Terminator (the strongest bow in the game, used for nearly all endgame content).",
    ],
  },
  {
    slug: "slayer-vampire",
    title: "Vampire Slayer — Riftstalker Bloodfiend",
    category: "slayers",
    summary: "A unique 5-tier boss kept in the Rift.",
    body: [
      "Riftstalker Bloodfiend is a unique boss, kept in the Rift. It has 5 tiers and is extremely unique. There's only 1 build path for equipment/weapons, so requirements/progression are left out.",
      "Unique Gear: Weirder Tuba (Slayer 4), Vampire Dentist Relic (Slayer 5). Both are very powerful — a legendary accessory and a buff tool with a number of uses.",
      "For details, there's a dedicated guide and a Youtube video that cover Vampire Slayer.",
    ],
  },
  {
    slug: "slayer-blaze",
    title: "Blaze Slayer — Inferno Demonlord",
    category: "slayers",
    summary: "The hardest boss in the game.",
    body: [
      "At long last, the Inferno Demonlord. Nether, blaze-based, and one hell of a fight.",
      "Due to existing high-quality guides, requirements and builds aren't covered in-depth here. Just know: it's a lot. If you're reading this section, you're probably not ready yet.",
      "Unique Gear: Firedust/Twilight Dagger (Slayer 2), Warning Flare (Slayer 3), Kindlebane/Mawdredge Dagger (Slayer 4), Tactical Insertion (Slayer 5), Pyrochaos/Deathripper Dagger + Alert Flare (Slayer 6), SOS Flare (Slayer 7).",
      "Items useful outside of Slayer: SOS Flare is the strongest buff/healing deployable in the game. Tactical Insertion is used for a variety of high-tier dungeon tactics. Inferno Minions are the best money-making minions in the game.",
    ],
  },
  {
    slug: "dungeons-intro",
    title: "What is The Catacombs?",
    category: "dungeons",
    summary: "The basics: dungeon items, stars, and unlocking the Catacombs.",
    body: [
      "Ah, and now we're here, The Catacombs. The first and only set of dungeon crawls, coming in 2 sets of 7 floors — Master Mode and Normal Mode. My goal here is to break down some \"walls\" to getting into Dungeons — this section is mostly gear progression and general \"suggestions,\" not detailed boss routes.",
      "What are The Catacombs? Starting at Combat 15, you unlock the Dungeon Hub, which unlocks The Catacombs — a set of procedurally-generated combat rooms with enemies, secrets, puzzles, and traps. At the end of each run, you'll face one of many bosses.",
      "Dungeon Items: some items are automatically Dungeon Items, or can be converted at the Dungeon Smith. A dungeon item gets a stat boost of 14-475% while in dungeons, according to your Catacombs level.",
      "Item Stars: Stars can be applied using essence, gained from a variety of sources, or purchased from the Bazaar after Catacombs level 20 — one of the biggest raw stat upgrades you can give any weapon.",
      "Before you Begin: A Dungeonbreaker makes getting Secrets simple. A Zombie, Skeleton, Sheep, or Lion pet is a fantastic starting point. 200-300 Magic Power is a big help moving forward. If you have a friend to do dungeons with, it's highly recommended, at least to start.",
    ],
  },
  {
    slug: "dungeons-starting",
    title: "Starting the Catacombs (F1-F3)",
    category: "dungeons",
    summary: "The Watcher, Bonzo, Scarf, and The Professor.",
    body: [
      "Catacombs 1-4: Rotten Armor, Skeleton Grunt Armor, and Heavy Armor are the first useable dungeon armor sets, dropped from early floor mobs. Super Cleaver, Undead Bow, Dark Goggles, Mender Helmet, and Stone Chestplate are dungeon items purchasable from Ophelia that give a decent stat boost right away. An Unstable/Young dragon set may out-perform these armors, even non-dungeonized.",
      "The Entrance's boss is The Watcher, who spawns undead — kill them and walk through the portal, no notable drops.",
      "Floor 1: face The Watcher again, then Bonzo the Clown. Phase 1 he spawns undead; phase 2 he resurrects with additional attacks including a balloon swarm. Drops: Recombobulator 3000s (Recombs), Fuming Potato Books (FPBs), the Bonzo Staff.",
      "Floor 2: your boss is Scarf, the Necromancer. Phase 1 fights his soldiers — Mage, Warrior, Priest, Archer. Kill the Priest first, then the Warrior; the rest are easy. Then Scarf himself fights you. Drops: Scarf's Studies, Adaptive Blade, the Adaptive Belt (used the entire rest of your catacomb career). Move on at Catacombs level 5.",
      "Catacombs 5, Floor 3: face The Professor. Phase 1 kill all 4 Guardians within ~3s of each other. Then fight the Professor — fairly easy until 750k health, when he merges with the 4 guardians, heals, and becomes far more powerful. Defeat this form to clear the floor.",
      "Clearing Floor 3 unlocks the next tier of Ophelia's gear — most notably the Hyper Cleaver and Shadow Goggles. Notable drop: Adaptive Armor. Farm floor 3 to grind Recombs until Catacombs level 9-10, then move on — Floor 4 is notably harder.",
    ],
  },
  {
    slug: "dungeons-early-mid",
    title: "Early-Mid Dungeons (F4-F6)",
    category: "dungeons",
    summary: "Thorn, Livid, and Sadan — the mid-game bosses.",
    body: [
      "Catacombs 8: use a Hyper Cleaver (melee), Dreadlord Sword + Shadow Goggles (mage), or replace your Machine Gun Shortbow with a Dragon Shortbow (archer). You can technically do Floor 4 at Catacombs 9, but Catacombs 10 with a fully-starred Unstable/Young (or Wise if mage) Dragon set is recommended.",
      "Catacombs 9, Floor 4: Thorn, the Spirit — spawns a massive swarm of passive mobs that ram, explode, and plant landmines on you. The goal: survive. Killing enough mobs spawns a Spirit Bear; kill it to pick up the Spirit Bow, the only thing that can damage Thorn. Repeat 4 hits and Thorn dies.",
      "If coordinated, a duo can use a Tribal Spear for the whole fight — it stuns Thorn so he can't run, but every hit makes him faster (including from the Spear), so once you start, don't stop.",
      "Drops: Spirit Shortbow, Spirit Sword, Spirit Pet, Spirit Boots/Wing/Bone. The important ones are the Bone Necklace, Spirit Pet, and Spirit Sceptre (crafted from Spirit Wing). Spirit Bones craft the Bone Necklace's other half, plus material for a Felthorn Reaper and Bonemerang.",
      "Floor 5: Livid, unironically easier than Floor 4 — one phase, 8 copies of himself with different skins; find the right one (or let mods find it) and beat him. Drops: Shadow Assassin Armor (all classes but mage), dungeonizable Juju Shortbow, Shadow Assassin Cloak. Livid Dagger and Shadow Fury exist but aren't recommended over Juju/Hyper Cleaver. Also drops Last Breath, a critical endgame utility item.",
      "Catacombs 19, Floor 6: Sadan, the Master Necromancer. Phases: a swarm of Terracotta Warriors and their allied Golems (defeat Terracottas twice, kill the golems), then he drops 4 Giants — kill them and Sadan rises for the final fight. The Terracotta Warriors take the most survivability to push through.",
      "Notable items: Ophelia's gear is maxed here (Giant Cleaver, Mender Crown, Death Bow, Steel Chestplate, Wither Goggles). The Bouquet of Lies becomes usable — arguably the most versatile weapon outside a Hyperion. The Soulweaver Gloves, the final Dungeon Equipment piece, becomes your new best friend. Others include Necromancer Armor, Giant's Sword, Summoning Ring, Necromancer Sword, Precursor Eye — Giant's Sword is a pricier, less versatile Bouquet, and the necromancy gear is mostly outclassed by Reaper Scythe.",
      "Play a lot of Floor 6 to reach Catacombs level for Floor 7.",
    ],
  },
  {
    slug: "dungeons-f7",
    title: "Reaching for Glory — Floor 7",
    category: "dungeons",
    summary: "Maxor, Storm, Goldor, Necron — the biggest, baddest dungeon.",
    body: [
      "Floor 7 — the gateway to hell. The biggest dungeon, the baddest bosses, and the best (and most expensive) loot. You'll likely spend the most time here of any floor.",
      "All-Classes Setup: Bonzo Staff, Dungeonbreaker, Aspect of the End, Spirit Leaps, Superboom TNT, flawless+ gems, Ancient reforge, Recombs. Bonzo Mask and Spirit Mask are very high value for survivability.",
      "Berserk: 700-900 MP. Armor — Necron/Reaper Mask/Golden Head, Necron Legs/Chest, Maxor Boots. Weapons — Bouquet of Lies, Giant Cleaver, Juju Shortbow, or Terminator. Pets — Legendary Lion, Skeleton, Golden Dragon, Blue Whale.",
      "Archer: same as Berserk but requires Juju/Terminator. Can use a Death Bow for bosses, focus on Skeleton/Golden Dragon Pet.",
      "Healer: 500-700 MP, Spirit Leaps, Mastiff armor (careful wish-cheesing), Wither Cloak Sword, Reaper Mask/Necron Chest/Legs/Maxor Boots. Pets focus on EHP and mobility — Blue Whale, Black Cat, Phoenix/Jellyfish for utility.",
      "Tank: 600-800 MP. Armor — Reaper Mask/Necron Chest/Legs/Maxor Boots, or Reaper Mask/3pc Goldor, both with Bonzo Mask and Spirit Mask. Weapons — Bouquet of Lies or Juju Shortbow on a budget, Astraea and Terminator off of one. Pets — Black Cat, Skeleton, Golden Dragon in clear (Baby Yeti nerfed, so Blue Whale or DPS pets instead).",
      "Mage: 600-900 MP.",
      "The Boss — you fight The Wither Lords: Maxor, Storm, Goldor, Necron. Maxor: collect 2 crystals and drop them on the pad while baiting Maxor into a laser (mage/berserk grab crystals, tank baits) — do it twice. Storm: clear wither skeletons, take cover under one of four pads when lightning strikes, draw Storm under the pillars and let them crush him twice. Goldor: a 4-section factory of terminal puzzles (color matching, Simon Says, a Galatea Beacon minigame, and a shootout game) — complete all terminals while running from Goldor, then lead him into the reactor and shoot him. Necron: the easiest of the 4 — just don't stand on his pad or he'll nuke you.",
      "Relevant Loot: Necron's Handle, Wither Catalyst, Implosion, Shadow Warp, Wither Shield — the 5 components of the Wither Blade. Wither Cloak Sword, a unique immunity item with many practical uses. All expensive, all take a long time — have fun playing this floor for a long, long time!",
    ],
  },
  {
    slug: "dungeons-m1",
    title: "Master Mode Floor 1",
    category: "dungeons",
    summary: "Nearly irrelevant — most players skip straight to M3.",
    body: [
      "Cata Level: M1 is nearly irrelevant — most players skip it (unlockable and playable catacombs-level wise). If you do play it, any reasonable cata level works.",
      "Magic Power: 800-900 MP is plenty for M1.",
      "Weaponry: Archer and Berserk should have a Terminator. Healer and Tank can get by with a Juju Shortbow or Bouquet of Lies. A Wither Cloak Sword and Ice Spray Wand help against minibosses. Mage pre-Cata 36 uses a Midas Sword, otherwise a Dark Claymore.",
      "Armor: mstars are optional. Mage sticks with Necrotic Wither Goggles + Necrotic/Loving Storm (RCM) and an LCM set (4pc Ancient Storm). Other classes use the floor's Golden/Diamond Head, Necron Chestplate/Legs, and Maxor Boots.",
      "Pets: a level 100 Legendary Skeleton suffices. Mage uses a Sheep or Crow until they get a Golden Dragon. Everyone can take a Baby Yeti (damage) or Blue Whale (EHP).",
    ],
  },
  {
    slug: "dungeons-m2",
    title: "Master Mode Floor 2",
    category: "dungeons",
    summary: "Nearly irrelevant — most players skip straight to M3.",
    body: [
      "Cata Level: M2 is nearly irrelevant — most players skip it. If you do play it, any reasonable cata level works.",
      "Magic Power: 800-900 MP is plenty for M2.",
      "Weaponry: same as M1 — Terminator for Archer/Berserk. Wither Impact weapons are a nice upgrade but optional. A Wither Cloak Sword and Ice Spray Wand help against minibosses. Mage pre-Cata 36 uses a Midas Sword, otherwise a Dark Claymore.",
      "Armor: mstars are optional. Mage sticks with RCM (Necrotic Wither Goggles + Necrotic/Loving Storm) and an LCM set (4pc Ancient Storm). Other classes use the floor's Golden/Diamond Head, Necron Chestplate/Legs, and Maxor Boots.",
      "Pets: a level 100 Legendary Skeleton suffices. Mage uses a Sheep or Crow until they get a Golden Dragon. Everyone can take a Baby Yeti (damage) or Blue Whale (EHP).",
    ],
  },
  {
    slug: "dungeons-m3",
    title: "Master Mode Floor 3",
    category: "dungeons",
    summary: "First floor where mastery gear starts to matter. Aim for Cata 30-34+.",
    body: [
      "Cata Level: M3 is the first floor worth taking seriously. Aim for C30-32 minimum, 34+ optimal.",
      "Magic Power: 1k MP suffices for all classes at M3.",
      "Weaponry: Archer and Berserk should have a Terminator. Wither Impact weapons are optional but a nice survivability/clear boost. Healer and Tank can get by with a Juju Shortbow or Bouquet of Lies. A Wither Cloak Sword and Ice Spray Wand help against minibosses. Mage pre-Cata 36 uses a Midas Sword, otherwise a Dark Claymore.",
      "Armor: mstars are optional. Mage sticks with Necrotic Wither Goggles + Necrotic/Loving Storm (RCM) and an LCM set (4pc Ancient Storm). Other classes use the floor's Golden/Diamond Head, Necron Chestplate/Legs, and Maxor Boots (50/50 Skeleton Master Chestplate at C36). Parties with a healer can bring a Mastiff set for wish cheese.",
      "Pets: a level 100 Legendary Skeleton suffices. If you have the money, a Level 200 Golden Dragon with Antique/Hephaestus Remedies replaces it. Mage uses a Sheep or Crow until they get a Golden Dragon. Everyone can take a Baby Yeti (damage) or Blue Whale (EHP).",
    ],
  },
  {
    slug: "dungeons-m1-3",
    title: "Beginning of Mastery (M1-M3)",
    category: "dungeons",
    summary: "M1-M2 are mostly skippable, but M3 starts to matter.",
    body: [
      "Cata Level: M1/M2 are nearly irrelevant — most players skip them (unlockable and playable, catacombs-level wise). M3, aim for C30-32 minimum, 34+ optimal.",
      "Magic Power: for M1/M2, target 800-900 MP if you play them. For M3, 1k MP suffices for all classes.",
      "Weaponry: even at M1, Archer and Berserk should have a Terminator. Wither Impact weapons are optional but a nice survivability/clear boost. Healer and Tank can get by with a Juju Shortbow or Bouquet of Lies, though never as good as a Terminator/Wither Impact weapon. A Wither Cloak Sword and Ice Spray Wand help against minibosses. Mage pre-Cata 36 uses a Midas Sword, otherwise a Dark Claymore.",
      "Armor: mstars are optional. Mage sticks with Necrotic Wither Goggles + Necrotic/Loving Storm (RCM) and an LCM set (4pc Ancient Storm). Other classes use the floor's Golden/Diamond Head, Necron Chestplate/Legs, and Maxor Boots (M7 uses 50/50 Skeleton Master Chestplate at C36). Parties with a healer can bring a Mastiff set for wish cheese.",
      "Pets: a level 100 Legendary Skeleton suffices. If you have the money, a Level 200 Golden Dragon with Antique/Hephaestus Remedies replaces it. Overlevelled — a Level 100 Black Cat in clear. Phoenix is good QoL. Mage uses a Sheep or Crow until they get a Golden Dragon. Everyone can take a Baby Yeti (damage) or Blue Whale (EHP).",
    ],
  },
  {
    slug: "dungeons-m4",
    title: "Master of Many (M4)",
    category: "dungeons",
    summary: "One of the biggest money floors in the game.",
    body: [
      "This floor is almost always run for money — the second-most profitable floor, only consistently beaten by M7.",
      "Cata Level: Healer is the sole class where cata doesn't really matter — target C42, most good parties are there. All other classes should be C45+ (C42 is doable).",
      "Magic Power: Tank/Healer — 1000-1200 MP. Berserk — at least 1200 MP. Archer/Mage — 1400+ MP.",
      "Weaponry: all classes but mage need a Terminator (7-8 stars fine) and a Wither Impact sword (usually Hyperion or Astraea). Wither Cloak Sword and Ice Spray Wand help against minibosses. Archer/Mage should pick up a Gyrokinetic Wand. Mage uses a Wither Impact Hyperion, a Chimera 5 Dark Claymore, and a Chimera 5 Ragnarock.",
      "Armor: all but mage — 7-8 star Gold/Diamond Thorn Head, 50/50 M7 skeleton master chestplate, Necron leggings, Maxor Boots. Mage — RCM set (Necrotic Wither Goggles + Necrotic/Loving Storm) and LCM set (4pc Ancient Storm). Tank/Healer — Bonzo Mask and Spirit Mask, tank can swap to Necron Chestplate in boss. Legion 5 and perfect Jasper Gems on all applicable pieces at this point.",
      "Pets: same tiering as before — Level 200 Golden Dragon highly recommended, Level 100 Black Cat if overlevelled, Phoenix for QoL, Sheep/Crow for mage until Golden Dragon, Baby Yeti or Blue Whale for last slot.",
      "Guides: a General M4 Guide plus role-specific guides exist for Healer, Mage, Berserk, Archer (Term & RCM), and Tank (Term & RCM).",
    ],
  },
  {
    slug: "dungeons-m5",
    title: "Master of Lots (M5)",
    category: "dungeons",
    summary: "",
    body: [
      "Cata Level: Tank/Healer can get away with C36-38. Archer/Berserk should be C42+, Mage C45+. Berserk is relied on less than Archer in this floor — a high-level LCM can practically solo everything.",
      "Magic Power: Tank/Healer ~1000 MP. Archer/Berserk 1200+ MP, Mage the same but ideally 1400+.",
      "Weaponry: all but mage need a Terminator (7-8 stars fine) and a Wither Impact sword. Wither Cloak Sword + Ice Spray Wand help against minibosses. Mage uses a Wither Impact Hyperion, Chimera 5 Dark Claymore, and Chimera 5 Ragnarock. Healer is deep in Secret Goblin territory — none of these weapons are required, but every one helps.",
      "Armor: all but mage — 7-8 star Gold/Diamond Livid Head, 50/50 M7 skeleton master chestplate, Necron leggings, Maxor Boots. Mage — RCM + LCM sets as before. Tank/Healer — Bonzo Mask and Spirit Mask, tank can swap to Necron Chestplate. Legion 5 and perfect Jasper gemstones on all applicable pieces.",
      "Pets: same as before, though a Skeleton is a bit more acceptable here than on M4. A Level 200 Golden Dragon is still highly recommended if possible.",
    ],
  },
  {
    slug: "dungeons-m6",
    title: "Master of Most (M6)",
    category: "dungeons",
    summary: "",
    body: [
      "Cata Level: Tank/Healer ~C40+. Archer/Berserk C45+. Mage C48+. Berserk relied on less than Archer — can be lower level with higher survival investment.",
      "Magic Power: Tank/Healer 1000-1200. Archer/Berserk 1200-1400. Mage 1400+.",
      "Weaponry: all but mage need a Terminator (as close to hypermax as possible) and a Wither Impact sword. Mage uses a Gyrokinetic Wand, Wither Impact Hyperion, Chimera 5 Dark Claymore, and Chimera 5 Ragnarock. Archer/Berserk also use a Gyrokinetic Wand. Healer, ever the secret goblin, technically doesn't require any of these, but it's nice to have.",
      "Armor: all but mage — 8-10 star Gold/Diamond Sadan Head, 50/50 M7 skeleton master chestplate, Necron leggings, Maxor Boots. Mage — RCM + LCM as before. Tank/Healer — Bonzo Mask + Spirit Mask (tank swaps to Necron Chestplate in boss; if really underlevelled, a 3pc Goldor set adds survivability, but shouldn't be needed with good DPS).",
      "Pets: a Skeleton is okay for berserk but really not recommended here. A Level 200 Golden Dragon with Antique/Hephaestus Remedies is basically mandatory. Overlevelled — Black Cat in clear. Phoenix for QoL. Mage uses a Sheep until Golden Dragon. Everyone can take a Legendary Jellyfish to buff potions at run start. Healer uses a Baby Yeti; everyone else sticks with damage or takes a Blue Whale for EHP.",
    ],
  },
  {
    slug: "dungeons-m7",
    title: "Master of All (M7)",
    category: "dungeons",
    summary: "The absolute endgame of Dungeons.",
    body: [
      "Requirements — All Classes: Hephaestus Remedies Golden Dragon, Black Cat, Phoenix Pet, Jellyfish (buffs potions), Infinileap/Superboom TNT, Dungeonbreaker, Bonzo Staff, Jerry-chine gun, Aspect of the End, Last Breath, Ice Spray, Rogue Sword, Weirder Tuba, Sword of Bad Health, Soul Eater Term, M7 50/50 Skeleton Master Chestplate, Gyrokinetic Wand, Cow Hat, Mithril Coat, Maxor Leggings, Wither Relic.",
      "These are considered baseline \"requirements\" — not a guarantee you'll find a party. For a \"good\" party, aim higher: Cata 50 DPS, 45 Tank/Healer, 1600+ MP on DPS classes.",
      "Healer: a BRAIN. Catacombs 36+, 1000+ MP, Wither Impact Weapon, Spirit Mask, Bonzo Mask. Job is to secret goblin, press wish, door, and avoid fighting anything.",
      "Tank: Catacombs 40+, 1000+ MP. Halberd of the Shredded, Astraea/Hyperion, Wither Cloak, Soul Whip. Gold/Diamond Head, Skeleton Master Chest, Necron Legs, Maxor Boots — hypermax with full Prot/Growth 7. Spirit Mask, Bonzo Mask, Tier 6+ Master Skull, Ender Relic. Pets — Crochet Tiger Plushie or Blue Whale for boss EHP; DPS pets at higher cata.",
      "Archer: Catacombs 47+, 1500+ MP. Spiritual Duplex Terminator (hypermax). Bonemerang (optional), Death Bow (8+ Star, Overload, P7). Diamond Necron Head, Necron legs, Maxor Boots (Necron boots should be hypermax for boss). Pet — Gold Claws/Heph Relic Ender Dragon for P5 boss DPS. Chimera 5 Ragnarock, Tier 7 Master Skull, Armorshred Arrows.",
      "Berserker: Catacombs 46+, 1400+ MP. Spiritual Duplex Terminator (hypermax). Diamond Necron Head, Necron legs, Maxor Boots (Necron boots hypermax for boss). Pet — Gold Claws/Heph Relic Ender Dragon for P5 boss DPS. Chimera 5 Ragnarock, Tier 7 Master Skull, Spring Boots.",
      "Mage: Catacombs 47+, 1300+ MP bare minimum. Swarm Hyperion (Heroic, Smite, Prosecute, GK7, perfect sapphires). Chimera 5 Withered/Fabled Hyperion. Chimera 5 Ragnarock (all strength boosts). Chimera 5 Withered Dark Claymore (every upgrade). Ancient Storm + Wither Goggles (10 star, for boss). Necrotic/Loving Wither Goggles + Storm set (goggles 10 star, storm 7-8 star, for clear). Tier 7 Master Skull. \"Recommended\" extras: Hype #2 (Fabled, Chimera 5, execute/triple strike), Spring Boots, Spirit Mask, Claymore #2.",
      "Equipment by class: in boss, all classes (mage included) use a Blended Bone Necklace, Waxed Shadow Assassin Cloak, Bloodshot Adaptive Belt, Blended Soulweaver Gloves. Players using a Wither Impact weapon for clear use a Blended Implosion Belt. Left Click Mage uses a Menacing Balloon Snake over Bone Necklace. Remember to frag your equipment pieces where possible.",
      "Q — What is a 50/50 M7 Skeleton Master Chestplate, and why use it? A — Naturally dropped dungeon armor has a quality level, capping at 50% stat buff plus a rarity buff for a better reforge; stats also scale with the floor dropped. At high catacombs levels you burn through arrows constantly — the Skeleton Master Chestplate means you never consume arrows, roughly a 5% damage drop from a Necron Chestplate for a huge time save between runs.",
      "Q — I keep getting kicked from parties, I'm too slow! A — There are a lot of M7 Roles parties running Floor 7 — a great place to start learning.",
      "Helpful guides: a Terminator Build guide (Soul Eater is now fixed — use it over Swarm again), a General M7 Guide and Mage Guide, plus role guides for Tank, Archer, Berserker, Healer, and Mage from the M7 Guides Discord.",
    ],
  },
  {
    slug: "kuudra",
    title: "Kuudra Guide",
    category: "combat",
    summary: "5 tiers, brief gear breakdown per role.",
    body: [
      "5 tiers. Need to complete the Nether questline to unlock Basic tier. 1000 rep for Hot, 3000 for Burning, 7000 for Fiery, 12000 for Infernal.",
      "Future77 published a fantastic youtube video breaking down progression, and the Kuudra Gang has in-depth guides and info.",
      "A brief gear breakdown (credit Future77): note previous tier equipment is generally required unless indicated otherwise.",
      "T1/2: Armor — 3/4 Storm + Wither Goggles (Loving/Necrotic), or 2/4 Magma Lord + Mithril Coat + Cow Hat/Racing Helm (or 4/4 Ember Armor). Pets — Black Cat, Sheep/Crow/Golden Dragon. Equipment — Implosion Belt, Gauntlet of Contagion. Weapons — Fire Veil Wand, full-scrolled Hyperion. Tools — Etherwarp AOTV, Kuudra Talismans, SOS Flare or Overflux Power Orb.",
      "T3/4: Burning+ Terror, enchants focused on mana. Golden Dragon Pet is now required; Skeleton Horse is good for key things. Duplex Terminator, 32+ Toxic Arrow Poison per run. Minimum 1100 MP. Stun Role — any drill/pickaxe in hotbar for Pickobulus.",
      "T5: Replace Wither Goggles with Infernal Aurora Helm; Terror upgrades to Infernal. Last Breath for the debuff.",
      "Stunner role: replaces RCM Terror with 4/4 Infernal Hollow, Hollow Wand. Replace Toxic Arrow Poison with Twilight Arrow Poison. Minimum 1400 MP.",
      "Duplex role: Full DPS Infernal Terror + Warden Helm/100m+ Crown of Avarice. Sword of Bad Health, Endstone Sword, Blazetekk Ham Radio, Chimera 3+ Ragnarock. Hephaestus Remedies Golden Dragon, 8/8 Rift Necklace, maxed David's Cloak, Gauntlet of Contagion (waxed), Bloodshot Primordial Belt. Hypermax Spiritual Duplex Terminator. Minimum 1450 MP (use Warrior stone until 1600 MP, then Hurtful).",
      "Rend role: 3/4 Reaper + Infernal Terror Helm. 3/4 Elegant Tuxedo, 100m+ Crown of Avarice (Warden if broke). Hypermax Spiritual Bonemerang, Atomsplit Terminator (skip if also stunning), same tools as Duplex. Bigger Teeth Golden Dragon + Heph Remedies Golden Dragon + Serrated Claws Blaze. Minimum 1700 MP.",
      "That's the brief version — the linked video goes much further in-depth.",
    ],
  },
  {
    slug: "foraging-hunting",
    title: "Foraging Progression",
    category: "foraging-hunting",
    summary: "From the Lumberjack's first quest through Galatea and the Starlyn Contest.",
    body: [
      "With the release of Galatea, foraging is finally starting to get more fleshed out.",
      "The Beginning — Before Galatea: start in the Hub, bring the Lumberjack 20 oak logs for a Promising Axe, then talk to Charlie in the park. Hop from park island to park island to collect the four pieces of Park Armor. Before departing to Galatea, get a Spruce Axe, a Treecapitator, and an Ocelot Pet (other pets aren't worth it until later).",
      "Park Objectives/Accessories: Campfire Badge + Campfire Trials (Legendary Accessory), Melody's Hair (Epic Accessory), Raider Sword (earlygame weapon/museum item, from Melancholic Viking), Wood Singularity (axe buff, also used for Blaze Slayer crafts), Woods Race (source of Wolf's Paw, Hunter Knife, Silky Lichen).",
      "Once at Galatea, just follow the quest prompts.",
      "Armor, Tool, and Equipment Progression: two new trees — Fig and Mangrove. Buy Canopy Armor from Amaury, upgrading to Figmail at Fig Collection 8. Treecapitator upgrades to Fig Hew (Fig Collection 4), then Figstone Splitter (level 6). Equipment — David's Cloak and Mangrove Equipment.",
      "Reforges: Groovy on armor, Moonglade on your axe. No equipment reforges affect Foraging Fortune or Sweep, so reforge is mostly irrelevant there.",
      "Foraging Pets: Ocelot (xp pet, push levels), Frog Pet (best general foraging pet until Jade Dragon), Jade Dragon (best overall, but an ungodly amount of xp — great if not rushing foraging).",
      "What to do: finish Hypixel's general quests, then talk to Hina for stable progression advice — otherwise, start whacking trees. And then there's Agatha and the Starlyn Contest — an upgraded Jacob's Contest, running for 20 minutes every 20 minutes. Everything interactive on Galatea earns points; after 20 minutes you get a placement and rewards including Heart of the Forest experience, Forest Whispers, and Agatha's Coupons.",
      "Agatha's Coupons buy upgrades from Agatha's Shop — Foraging Fortune boosts, Sweep Buffs, Frog Pet & upgrades, the Moonglade Artifact, bird shards, and more. Heart of the Forest (made into Foraging) grants Forest Whispers, used to upgrade perks — gained from cutting trees, tree gifts, berries, and Starlyn Contests.",
      "For a deeper look, Live Omen has a comprehensive Galatea guide. That's kinda all for foraging — chop trees, buy stuff. Now then, onto hunting!",
    ],
  },
  {
    slug: "hunting",
    title: "Hunting Guide",
    category: "foraging-hunting",
    summary: "Attributes, shards, and how to catch them.",
    body: [
      "Introduced alongside Galatea, Hunting replaces the old Attributes system with new permanent buffs via Attribute shards. Siphon shards through your attribute bag (/shards) to consume them for a permanent buff, or fuse them at the Fusion Machine for stronger upgrades.",
      "There's almost 200 different shards, and a number of ways to obtain them.",
      "Rarities and Siphon Requirements: Common (Hunting 0, 96 siphons to max), Uncommon (Hunting 5, 64), Rare (Hunting 10, 48), Epic (Hunting 15, 32), Legendary (Hunting 20, 24).",
      "Salts: the easiest hunts — consume a Salt, kill the mobs that drop the matching shard. Currently available from Lushlilac and Candycombs.",
      "Huntrap Hunts: from the Silver Wood collection (gained via Fig Tree gifts). Place them down and let them catch stuff — check the 7th column of the Attributes wiki for huntrap-eligible creatures.",
      "Lasso Hunts: unlocked from the Vinesap collection. Right-click to throw the lasso at your target and reel them in near the indicator before they disappear — some creatures need multiple catch-bar depletions.",
      "Fishing Net Hunts: for Water Attribute creatures, unlocked through the Sea Lumies collection. The net damages sea creatures — depending on the creature it instantly catches them, does something else, or lowers their HP. As a rule, it's ill-advised to overuse on creatures where it does something else.",
      "Huntaxes: the most commonly used hunting combo, unlocked from the Vinesap collection. A Black Hole automatically \"catches\" a monster below 10% HP; you can do this with normal weapons too, but a Huntaxe can't kill the target and prevents others from damaging your hunt target (anti-griefing).",
      "Fusions: Skyshards.com shows what fuses into what. Normal Mode assumes buying the most efficient shards to upgrade; Ironman Mode has the full fusion tree with 0 shortcuts. Example — a Jormung Shard (Legendary): Normal Mode buys 5x Kraken + 5x Power Dragon via bazaar per shard. Ironman Mode instead combines Ghosts (from Lapis Zombie/Glacite Miner) with Verdants (from Lapis Creeper) to get Kraken, then combines Burningsoul with Verdant for Power Dragon shards.",
      "Levelling: Hunting can be painful to level early. If you have money and setup already, hunting Ghosts is widely considered fastest (needs 800-950k/hit) — numerous, and can use a Huntrap. If you're not far along and Ghosts are hard to kill, Glacite Miners work well too.",
    ],
  },
  {
    slug: "hunting-shards",
    title: "Best Bang-for-Buck Shards",
    category: "foraging-hunting",
    summary: "The universally good attribute shards for any content.",
    body: [
      "There's specifics for all content, but here are the best \"bang for buck\" options that are good for basically everything:",
      "Shellwise (Epic) — at max experience, grants knockback immunity, replacing an item that used to be required for everything.",
      "Golden Ghoul (Common) — 10 coins per kill, which adds up massively.",
      "Obsidian Defender (Uncommon) — 10 speed.",
      "Sycophant (Uncommon) — heals 1% of max health on kill; each Vampirism tier adds 1%, effectively a T7 Vampirism that works on all weapons, not just swords.",
      "Soul of the Alpha — 1% more damage per Grandma Wolf pet combo (max 50). In dungeons, that's a 50% damage boost off a passive Grandma Wolf.",
      "All Ruler/Resistance Perks — 40 defense / 30% damage against relevant mobs, extra inventory bag slots, catacombs loot, crystal nucleus loot.",
      "All Elemental Perks — free health/intelligence/strength stats.",
      "Kada Knight — Lifeline, 25% damage and defense boost at low HP.",
      "Thorn — 15% damage buff at full health.",
      "Barbarian Duke X — 25% bonus melee damage.",
      "End Stone Protector — 2% global defense buff.",
      "Kraken — 20 vitality.",
      "Daeman — 10% RNG meter refill rate.",
      "Inferno Demonlord — 10 bonus attack speed.",
      "Cinderbat — 5 Magic Find.",
      "Jormung/Etherdrake — 1% strength/crit damage boost.",
      "This is just SOME of what's available — every one is a permanent, unconditional buff. If you're a returning player, you might recognize some of these as perks tied to very rare and expensive armor pieces — now basically free and universal.",
    ],
  },
  {
    slug: "hunting-why",
    title: "But Where's the Money?",
    category: "foraging-hunting",
    summary: "Hunting isn't the best money maker — but it supplements everything else.",
    body: [
      "Hunting and Foraging aren't the best source of money yet. What they DO give you is the single biggest supplement to every other source of content in the game.",
      "You followed the Enderman guide, have Burning Crimson, Atomsplit, 900 magic power, but keep dying? Check your attributes. You might be missing Ender Ruler and Elite — a blatant 60% damage boost against ender bosses. You might be missing Endstone Protector, Ender Resistance, and Lifeline — +30/2% defense, and a conditional 25% boost. Or Barbarian Duke X — 25% melee damage isn't to be scoffed at.",
      "This is just a glimpse of what Hunting gives you.",
      "Oh, and it can make a bit of money too. Shards like Shellwise, Invisibug, Coralots, and Zombie Miner are all quite high value.",
    ],
  },
  {
    slug: "minions",
    title: "Minion Guide",
    category: "minions",
    summary: "Earlygame setup, money minions, and self-upgraders.",
    body: [
      "\"But if Skyblock has taught me anything, it's that if you have a problem, the answer is slavery.\" — Technoblade, The Great Potato War",
      "Earlygame: highly recommend 1-2 Fishing or Clay Minions, then ALL on Redstone Minion — Redstone collection controls your Accessory Bag, the most important piece of the game for improving overall damage.",
      "After Redstone and Fishing collections are maxed, you have choices:",
      "Collections: use minions to upgrade more tedious collections — annoying Mining, Mob, or Fishing Collections. Common Collection Minions: Vampire, Ghast, Farm Animal Minions.",
      "Money: minions used to be much better for money than now, but a few still make decent money. Budget — Snow, Clay, Wheat, Potato, Pumpkin Minions (Super Compactor, Diamond Spreading). Slime Minions (Corrupt Soil, Enchanted Hopper, minion speed upgrades). Given market instability, use the Hyminions website to calculate rates.",
      "Late/endgame: Inferno Minions (best money-making minions, see a dedicated guide), Tarantula Minions (T9+ best upgrades), Revenant Minions (T9+ best upgrades, only worth it in a lategame co-op with 7+ people).",
      "Realistically the cheapest okay-ish money option is toward the top. Personally lean Clay for fishing xp, and Chicken for money — Clay costs ~800k/minion, Chicken ~3m, but Chicken is 2-3x as profitable with the same setup. Hyminions gives a lot of insight into minion options (numbers aren't 100% accurate).",
      "Minion Self-Upgraders: upgrading minions unlocks more slots. Annoying collections are sometimes worth placing minions on, to \"save\" resources to upgrade them off their own profits — though it's almost always worth just buying the materials directly.",
      "Notable Minion Items: Super Compactor/Dwarven SC (auto-enchants/smelts, mandatory on almost all minions — be aware of what you shouldn't smelt). Diamond Spreading (cheapest extra money, spawns Diamonds from Collections). Minion Expander (slight speed boost). Lesser/Soulflow Engine (generates Soulflow, used for Enderman Slayer items). Mithril Infusion (permanent minion speed buff, consumable). Flycatcher (big speed buff). Free Will (consumable permanent speed buff, 50%+4%/minion level success rate). Postcard (obtained when a Free Will fails — place for a 5% speed buff to all minions).",
    ],
  },
  {
    slug: "other-skills",
    title: '"Other" Skills',
    category: "other-skills",
    summary: "Enchanting, Alchemy, Carpentry, and Taming.",
    body: [
      "Enchanting: one of the easiest skills to max — controls what Enchantments you can use, ability damage, and which tier of the Experimentation Table you can access.",
      "Experimentation Table: get mods (NEU or Skyhanni make this easy) with Solvers. Three memory-game sections: Chronomatron (Simon Says — remember the order), Ultrasequencer (also remember-the-order, but colors popping up on screen), and Superpairs (the key one — a \"remember the matches\" game for experience, enchanting bottles, and rare books). More clicks come from Metaphysical Serums, and from scoring well on Chronomatron/Ultrasequencer.",
      "Alchemy: everyone's least favorite. Two main methods to level it: Step 1 — Absorption-related brewing (first in the Hub). Step 2 — Enchanted Gold Blocks/Enchanted Sugar Cane. Step 3 (optional, to regain costs) — Enchanted Glowstone. Step 4 — repeat, repeat, repeat (the only functional autobrewers are a nightmare to build). SBM has an externally created Alchemy guide.",
      "Carpentry: a passive skill that increases collection value — refer to the Craft Flipping segment for ideas on what to craft and sell to speed leveling without losing money. If money isn't an object, manually crafting Diamond Blocks up to perfect T13 armor and selling is widely considered the fastest way to level it (museum it after for extra xp, though you'll lose a lot of value doing so fast). Sq has a guide in the discord server, plus a live-data spreadsheet for craft costs and sale prices.",
      "Taming: you can bump the level cap to 60 by giving rare and expensive pets to a scammer.",
    ],
  },
  {
    slug: "flipping",
    title: "The Art of Manipulation — Bazaar & Auction Flipping",
    category: "money",
    summary: "Bazaar flipping, craft flipping, sniping, and lowballing.",
    body: [
      "The Bazaar and Auction are the player-controlled money making methods, and arguably the most unique part of this game — a diverse, almost fully user-controlled market, where profits are controlled by your own understanding of how people work.",
      "To open this up: SkyCofl, a free (with paid options) website with mod integrations. It shows what flips have profit, and lists auction items posted far below their normal BIN. The free version has a ~20-40s delay; paid versions ~0-5s, since a lot of people illegally bot-snipe those items nearly instantly.",
      "Bazaar Flipping: buy order low, sell order high. Find items with decent profits — most consistently, event-driven items (e.g. event items like Glowstone during certain events).",
      "Craft Flipping: tedious — buy low-end materials in buy orders, sell-order the upgraded versions. Common flips: Enchanted Melon Blocks, Super Compactors, Aspect of the End, Null Blades. Look at items in high demand that are annoying to craft, or have weird collections. Some auction-based craft flips: Prismarine Blade and Bow, Ragnarocks, Zombie Artifacts.",
      "Auction Flipping/Sniping: best done with SkyCofl or SkyHanni-style value mods. Find items under lbin, snipe, resell at profit. More tedious, and due to premium Cofl users and botters, hard to make notable profit — though decent profit is possible. Not as decent as...",
      "Lowballing (also known as scamming): DO NOT DO THIS without a good bank. Run around populated lobbies with a message offering to buy items, or wait for people to visit your island wanting to sell a lot of items instantly for less profit. As a rule, aim for ~10-25% discount using Skyhanni for lbin/Estimated Item Value — go lower discount for high-demand items (~8-10% if 100 sell/day), higher for low-demand items. If the seller seems dumb, take advantage. This takes advantage of another player's impatience — of all the money making methods in the game, Lowballing is definitely the highest potential.",
    ],
  },
  {
    slug: "lazy-money",
    title: "The Lazy Man's Money Making Methods",
    category: "money",
    summary: "Forge flipping and pet leveling/flipping — methods that make themselves.",
    body: [
      "Forge Flipping: very simple. Throw stuff in the Forge, sell on the bazaar. Easy to find profits, easy to sell. To start, Refined Diamonds and Gold/Mithril Plates are recommended. Most Skyblock discord servers have a /forgeprofit command in their bot channels.",
      "Pet Levelling and Flipping: some pets are a consistent profit just raw-upgraded — e.g. Lion Pet or Skeleton Pet. For peak efficiency, always have something cooking in Kat that sells well — Hedgehog, Ammonite, Lion, Enderman, and Mithril Golem Pets are recommended.",
      "Use experience shares to level up high-value pets and sell them for even more profit. An epic Enderman Pet at level 1 might sell for 100k, but at level 100, it'll sell for 20-30m. Find stuff like that, and go from there.",
    ],
  },
  {
    slug: "rift-money",
    title: "Money Making — The Rift",
    category: "money",
    summary: "20-50m/hr for minimal setup.",
    body: [
      "The Rift is an alternate universe, accessed through the Wizard's Tower. You get three free entries a day through the portal at the top; after that, pay the Wizard 32 Grand Experience Bottles or 200 bits to \"recharge\" your entries (which refresh daily).",
      "Once inside, you have a certain amount of Rift Time. You start with nothing — you can't transfer normal gear in — you have to get it all yourself, though there's a good few items you CAN transfer in and out.",
      "Due to plenty of adequate guides already existing, this won't go too in-depth, but the methods make easily 20-50m/hr with minimal setup time and effort.",
      "Recommended guides: SBM's Rift Guide, Yadi's Rift Guide (to mountaintop), Yadi's Rift Guide (plus mountaintop), and Yadi's Rift Money Making Method Guide.",
      "Rift-Transferrable Items include: 1 Legendary Accessory, Eleanor's Armor (good for Ghost farming), Weirder Tuba (good stat buffer for Combat).",
    ],
  },
  {
    slug: "dailies",
    title: "A Short Guide to Daily Tasks",
    category: "ideas",
    summary: "Small daily habits that compound into big gains.",
    body: [
      "Enchanting Skill: controls what enchantments you can use, providing a massive buff to overall damage. Level it up using your Experimentation Table daily — it stores up to 3 Charges and grants enchanting xp, experience bottles, and even rare potions/books. Do these daily!",
      "Mining Skill: every day, your first few Commissions get a big boost. If you're just floating while deciding what to do, these are a great little thing to knock out.",
      "Dungeons: every day, your first five dungeon runs get a big Catacombs xp boost. Your Catacombs level multiplies your items and equipment stats in dungeons, and is the most important stat for your entire dungeon career.",
      "Crimson Isle: once there, join a faction and complete quests for reputation, which lets you fight higher tiers of Kuudra. You can also visit the Matriarch and Aranya for valuable rewards — a dedicated guide covers more \"dailies\" for reputation.",
    ],
  },
];

export function getGuide(slug: string): Guide | undefined {
  return GUIDES.find((g) => g.slug === slug);
}

export function getGuidesByCategory(category: string): Guide[] {
  return GUIDES.filter((g) => g.category === category);
}

export function searchGuides(query: string): Guide[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return GUIDES.filter(
    (g) =>
      g.title.toLowerCase().includes(q) ||
      g.summary.toLowerCase().includes(q) ||
      g.body.some((p) => p.toLowerCase().includes(q))
  ).slice(0, 12);
}